core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('product/', include('product.urls')),
    path('support/', include('support.urls')),
    path('photo/', include('photo.urls')),
    path('morpheme/', include('morpheme.urls')),
    path('ml/', include('ml.urls')),
    path('rtc/', include('rtc.urls')),

    path('accounts/register/add/', UserCreateDoneTV.as_view(), name='register_add')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ml/urls.py
from django.urls import path

from ml import views
from ml.views import MLIndexLV, textrank

app_name = 'ml'
urlpatterns = [
    path('', MLIndexLV.as_view(), name='index'),
    path('textrank/', views.textrank, name='textrank'),
]

morpheme/urls.py
from django.urls import path

from .views import *

""" app_name이 꼭 있어야 core/urls.py에서 인식함 """
app_name = 'morpheme'

urlpatterns = [
    # ex : /morpheme/, parameter : context path, view name, view role
    path('', MorphemeMainCreateView.as_view(), name='morpheme_index'),

    path('sentence/', SentenceAnalyzeLV.as_view(), name='get'),

    path('morpheme_file/', FileAnalyzeLV.as_view(), name='file_add'),
]

photo/urls.py
from django.urls import path

from .views import *


app_name = 'photo'

urlpatterns = [

    # Example: /
    path('', PhotoLV.as_view(), name='index'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),


    # Example: /photo/add/
    path('photo/add/',
         PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    path('photo/change/',
         PhotoChangeLV.as_view(), name="photo_change",
         ),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/',
         PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/',
         PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

product/urls.py
from django.urls import path

from .views import *



app_name = 'product'
urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),

    # Example: /add/
    path('add/',
         ProductCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         ProductChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         ProductUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         ProductDeleteView.as_view(), name="delete",
    ),
]

morpheme/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.text import slugify
from konlpy.tag import *
import uuid

morpheme_lists = (
    ('', u'선택'),
    ('mecab', u'mecab'),
    ('jiana', u'jiana'),
    ('kkma', u'kkma'),
    ('komoran', u'komoran'),
    ('okt', u'okt'),
    ('hannanum', u'hannanum')
)

date_input_format = ['%Y-%m-%d %H:%M:%S']


class MorphemeAnalysisModel(models.Model):
    auto_increment_id = models.AutoField(primary_key=True, default=uuid.uuid1)
    raw_sentence = models.CharField(max_length=300, verbose_name='원문 문장', name='raw_sentence')
    slug = models.SlugField(unique=True, allow_unicode=True, help_text='one word for title alias.', name='slug', default=uuid.uuid1)
    morpheme_type = models.CharField(max_length=1, verbose_name='형태소분석기', choices=morpheme_lists, name='morpheme_type')
    file = models.FileField(
        upload_to='files/%Y/%m',
        name='file',
        default=None,
        null=True,
        blank=True,
        validators=[FileExtensionValidator(["csv"], message="CSV 파일만 허용 가능")]
    )

    reg_date = models.DateTimeField(auto_now_add=True)

    user_name = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'analysis'
        db_table = 'morpheme_analysis'

    def save(self, *args, **kwargs):
        if not self.auto_increment_id:
            self.slug = slugify(self.slug, allow_unicode=True)
        else:
            self.auto_increment_id = MorphemeAnalysisModel.objects.count()
        super(MorphemeAnalysisModel, self).save(*args, **kwargs)


class Morpheme(models.Model):
    sentence = models.CharField(max_length=300)
    title = models.CharField(max_length=300)

    class Meta:
        verbose_name = 'morpheme'
        verbose_name_plural = 'morphemes'
        db_table = 'morpheme_morpheme'

    @staticmethod
    def morpheme_init(morpheme_type):
        print(morpheme_type)
        morpheme_object = None
        if morpheme_type == 'mecab':
            morpheme_object = Okt()
        elif morpheme_type == 'okt':
            morpheme_object = Okt()
        elif morpheme_type == 'komoran':
            morpheme_object = Komoran()
        elif morpheme_type == 'hannanum':
            morpheme_object = Hannanum()
        elif morpheme_type == 'kkma':
            morpheme_object = Kkma()
        elif morpheme_type == 'jiana':
            # morpheme_object = Jiana()
            morpheme_object = Okt()
        return morpheme_object

    @staticmethod
    def pos_list(obj, data_frame):
        print(obj)
        for j in range(len(data_frame)):
            doc_number = str(data_frame['docNumber'][j])
            speaker_type = data_frame['speakerType'][j]
            sentence = data_frame['sentence'][j]
            yield [doc_number, speaker_type, obj.pos(sentence)]

    def __del__(self):
        print("delete object")

morpheme/forms.py
from django import forms
from .models import *


class SentenceForm(forms.Form):
    morpheme_choices = (
        ('', u'선택'),
        ('mecab', u'mecab'),
        ('jiana', u'jiana'),
        ('kkma', u'kkma'),
        ('komoran', u'komoran'),
        ('okt', u'okt'),
        ('hannanum', u'hannanum')
    )

    morpheme_type = forms.ChoiceField(choices=morpheme_choices, label='형태소 분석기')
    raw_sentence = forms.CharField(max_length=300, label='원문정보')
    parsed_sentence = forms.CharField(max_length=300, label='변환정보 ',
                                      widget=forms.TextInput(attrs={'readonly': 'readonly'}))


class MorphemeAnalysisForm(forms.ModelForm):
    class Meta:
        model = MorphemeAnalysisModel
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(MorphemeAnalysisForm, self).__init__(*args, **kwargs)
        self.fields['morpheme_type'].widget = forms.Select(choices=morpheme_lists, attrs={'id': '', 'required': 'required'})
        self.fields['raw_sentence'].widget = forms.TextInput(attrs={'required': 'required', 'v-on:keyup.13':'sentence_analyze'})
        self.fields['file'].required = 'required'

    def save(self, commit=True):
        morpheme = super().save(commit=False)
        print(morpheme, " : ", commit)
        if commit:
            morpheme.save()
        return morpheme

morpheme/views.py
import gc
import io
import os
import time

import jpype
import pandas
import psutil
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView

from .forms import MorphemeAnalysisForm
from .models import MorphemeAnalysisModel, Morpheme


def decorator_function(get):
    def wrapper_function(*args):
        return get(*args)

    return wrapper_function


def process_check():
    process = psutil.Process(os.getpid())
    memory = process.memory_info().rss / 1024 / 1024

    for proc in psutil.process_iter():
        if proc.name() == "python.exe":
            print(proc)
    return memory


class MorphemeMainCreateView(LoginRequiredMixin, CreateView):
    template_name = 'morpheme/morpheme_list.html'
    form_class = MorphemeAnalysisForm
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('morpheme:morpheme_index')


class SentenceAnalyzeLV(ListView):
    template_name = 'morpheme/morpheme_list.html'

    def post(self, request):
        morpheme_type = '%s' % self.request.POST.get('morpheme_type')
        sentence = '%s' % self.request.POST.get('raw_sentence')
        user_name = '{0}'.format(self.request.user)

        start_time = time.time()
        before_memory = process_check()

        morpheme = Morpheme()
        morpheme_object = morpheme.morpheme_init(morpheme_type)
        result_sentence = morpheme_object.pos(sentence)

        after_memory = process_check()
        end_time = time.time()
        total_time = end_time - start_time
        total_memory = after_memory - before_memory

        del morpheme
        jpype.java.lang.System.gc()
        gc.collect()

        context = {}
        context['result_sentence'] = list(result_sentence)
        context['morpheme_type'] = morpheme_type
        context['total_memory'] = float('{:.3f}'.format(total_memory))
        context['user_name'] = ''.join(char for char in user_name if char not in '"')
        context['total_time'] = float('{:.3f}'.format(total_time))

        model = MorphemeAnalysisModel(raw_sentence=sentence, morpheme_type=morpheme_type)
        model.save()

        return JsonResponse(context, json_dumps_params={'ensure_ascii': True})


class FileAnalyzeLV(ListView):
    template_name = 'morpheme/morpheme_list.html'

    def post(self, request):
        file_morpheme_type = '%s' % self.request.POST.get('morpheme_type')
        filename = request.FILES['csv_file'].read()

        data_frame = pandas.read_csv(io.BytesIO(filename))
        morpheme_object = Morpheme.morpheme_init(file_morpheme_type)
        morpheme_list = Morpheme.pos_list(morpheme_object, data_frame)
        del morpheme_object
        jpype.java.lang.System.gc()
        model = MorphemeAnalysisModel(raw_sentence=filename, morpheme_type=file_morpheme_type, file=request.FILES['csv_file'])
        model.save()

        return JsonResponse(self.get_data(file_morpheme_type, morpheme_list))

    @staticmethod
    def get_data(file_morpheme_type, morpheme_list):
        return {
            'file_morpheme_type': file_morpheme_type
            , 'morpheme_list': list(morpheme_list)
        }

morpheme/templates/morpheme/detail.html
{#<h1>{{ question.question_text }}</h1>#}
{##}
{#{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}#}
{##}
{#<form action="{% url 'polls:vote' question.id %}" method="post">#}
{#{% csrf_token %}#}
{#{% for choice in question.choice_set.all %}#}
{#    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">#}
{#    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>#}
{#{% endfor %}#}
{#<input type="submit" value="Vote">#}
{#</form>#}

morpheme/templates/morpheme/file_form.html
{% load staticfiles widget_tweaks %}


{% block content %}
    {% if form.is_multipart %}
        <form class="form-horizontal" id="file_form" enctype="multipart/form-data" method="post" action="."
              onsubmit="return false">
    {% else %}
        <form class="form-horizontal" method="post" action=".">
    {% endif %}
{% csrf_token %}

<fieldset style="border:1px solid #ccc; padding:20px 0 0 0;">

    <div class="form-group">
        <label for="id_file_morpheme_type" class="col-sm-3 control-label">{{ form.morpheme_type.label }}</label>
        <div class="col-sm-8">
            {{ form.morpheme_type|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group">
        <label for="id_csv_file" class="col-sm-3 control-label">{{ form.file.label }}</label>
        <div class="col-sm-8">
            {{ form.file|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-10 col-sm-4">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>
    </div>

    <div class="form-group">
        <label for="id_csv_file" class="col-sm-1 control-label"></label>
        <div class="col-sm-10" style="width:90%">
            <div class="alert alert-info" id="file_result_info" style="overflow:auto !important"></div>
        </div>
    </div>
</fieldset>
</form>

<script type="text/javascript">
    $(document).ready(function () {
        $('input[type="submit"]').on("click", function () {
            file_analyze();
        });
    });

    function build_form_data() {
        let form_data = new FormData();
        let morpheme_type = document.getElementsByName("morpheme_type")[1].value;
        let csv_file = $('#id_file')[0].files[0];
        let csrftoken = $("input[name='csrfmiddlewaretoken']").val();

        form_data.append("morpheme_type", morpheme_type);
        form_data.append("csv_file", csv_file);
        form_data.append("csrfmiddlewaretoken", csrftoken);
        return form_data
    }

    function file_analyze() {
        if (confirm('파일을 업로드하시겠습니까?')) {

            /* 1. set form_data */
            let form_data = build_form_data();
            for (let key of form_data.entries()) {
                if (key[1] == 'undefined' || key[1] == '') {
                    return false;
                }
            }

            if ($("#id_file") != null && $('#id_file_morpheme_type').val() != '') {
                $.ajax({
                    url: "/morpheme/morpheme_file/"
                    , enctype: 'multipart/form-data'
                    , type: 'post'
                    , contentType: false
                    , processData: false
                    , data: form_data
                    , beforeSend: function () {
                        $('.load_spinner_class').css('width', '100%').css('height', '100%').css('background-color', 'black').css('opacity', '0.2').css('z-index', '0');
                        $('.load_spinner_class *').prop('disabled', true);
                    }
                    , success: function (json) {
                        console.log(json.morpheme_list);
                        var morpheme_type_str = JSON.stringify(json.file_morpheme_type);

                        $("#file_result_info").html('<p><strong>' + morpheme_type_str + ' 분석결과 </strong></p>');
                        for (var i = 0; i < json.morpheme_list.length; i++) {
                            var doc_number = json.morpheme_list[i][0];
                            var speaker_type = json.morpheme_list[i][1];
                            var sentence_list = json.morpheme_list[i][2];
                            var sentence = ''
                            for (var j = 0; j < sentence_list.length; j++) {
                                sentence += sentence_list[j] + ' ';
                            }
                            $("#file_result_info").append('<p>[' + doc_number + ']번째 문장 : ' + '화자 : ' + speaker_type + ', ' + sentence + '</p>');
                        }
                    }
                    ,
                    error: function (xhr, errmsg, err) {
                        console.log(xhr.status + ": " + xhr.responseText);
                    }
                    ,
                    complete: function () {
                        $('.load_spinner_class').css('width', '100%').css('height', '100%').css('background-color', '').css('opacity', '1').css('z-index', '0');
                        $('.load_spinner_class *').prop('disabled', false);
                    }
                });
            } else {
                return false;
            }
        } else {
            return false;
        }
    }
</script>
{% endblock %}

morpheme/templates/morpheme/morpheme_change_list.html
{% extends "base.html" %}

{% block title %}morpheme_change_list.html{% endblock %}

{% block content %}

    <h1>Photo Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="info">
            <th class="col-md-2">Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description|linebreaks }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

morpheme/templates/morpheme/results.html
{#<h1>{{ question.question_text }}</h1>#}
{##}
{#<ul>#}
{#{% for choice in question.choice_set.all %}#}
{#    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>#}
{#{% endfor %}#}
{#</ul>#}
{##}
{#<a href="{% url 'morpheme:detail' question.id %}">Vote again?</a>#}
{##}

morpheme/templates/morpheme/sentence_form.html
{% load staticfiles widget_tweaks %}


{% block content %}
    {#    <h1>문장별 실시간 형태소 분석 - {{user}}</h1>#}
    {#    <p class="text-muted">아래 입력창에서 형태소 분석엔진을 선택하고 문장을 입력해주세요.</p>#}
    <div id="sentence-result">
        <form id="sentence_form" class="form-horizontal" action="." method="post" onsubmit="return false">{% csrf_token %}

            <fieldset style="border:1px solid #ccc; padding:20px 0 0 0;">
                <div class="form-group">
                    <label for="id_morpheme_type" class="col-sm-3 control-label">{{ form.morpheme_type.label }}</label>
                    <div class="col-sm-8">
                        {{ form.morpheme_type|add_class:"form-control" }}
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_raw_sentence" class="col-sm-3 control-label">{{ form.raw_sentence.label }}</label>

                    <div class="col-sm-8">
                        <div class="input-group">
                            {{ form.raw_sentence|add_class:"form-control" }}
                            <span class="input-group-addon" v-on:click="sentence_analyze"><i
                                    class="glyphicon glyphicon-search"></i></span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label for="id_parsed_sentence" class="col-sm-3 control-label">변환 문장</label>
                    <div class="col-sm-8">
                        <div class="alert alert-info" id="result_info">
                            <li v-for='result in result_set' v-text="result">
                                {{ result }} - {{ index }} -
                            </li>
                            {{ result_set.morpheme_type }}
                            aaaaaaaa : {{ morpheme_type }}
                        </div>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
    <script>

        let sentence_result = new Vue({
            el: '#sentence-result'
            , data: {
                result_set: [1,2,3,4,5]
            },
            methods: {
                sentence_analyze: function () {
                    let morpheme_type_param = document.getElementsByName('morpheme_type')[0].value;
                    let raw_sentence_param = document.getElementsByName('raw_sentence')[0].value;
                    let csrf_token_param = document.getElementsByName('csrfmiddlewaretoken')[0].value;

                    let params = new URLSearchParams();
                    params.append('morpheme_type', morpheme_type_param);
                    params.append('raw_sentence', raw_sentence_param);
                    params.append('csrfmiddlewaretoken', csrf_token_param);

                    if (morpheme_type_param != '' && raw_sentence_param != '') {
                        //axios.post('/morpheme/sentence/', params).then(response => {
                        axios.post('/morpheme/sentence/', params).then(response => {

                            this.result_set.push(
                                {morpheme_type: response.data.morpheme_type},
                                {result_sentence: response.data.result_sentence},
                                {total_memory: response.data.total_memory},
                                {user_name: response.data.user_name},
                                {total_time: response.data.total_time}
                            )

                            /*
                            this.result_set.morpheme_type = JSON.stringify(response.data.morpheme_type);
                            this.result_set.result_sentence = JSON.stringify(response.data.result_sentence);
                            this.result_set.total_memory = JSON.stringify(response.data.total_memory);
                            this.result_set.user_name = JSON.stringify(response.data.user_name);
                            this.result_set.total_time = JSON.stringify(response.data.total_time);
*/

                            console.log(this.result_set)
                        });

                    } else {

                    }
                }
            }
        });

        /*
        function sentence_analyze() {
            alert("A")
            $("#id_morpheme_type").attr('required', 'required');
            $("#id_raw_sentence").attr('required', 'required');

            if ($("#id_morpheme_type").val() != '' && $("#id_raw_sentence").val() != '') {
                $.ajax({
                    url: "/morpheme/sentence/"
                    , type: $("#sentence_form").method
                    , data: $("#sentence_form").serialize()
                    , beforeSend: function () {
                        $('.load_spinner_class').css('width', '100%').css('height', '100%').css('background-color', 'black').css('opacity', '0.2').css('z-index', '0');
                        $('.load_spinner_class *').prop('disabled', true);
                    }
                    , success: function (json) {
                        const morpheme_type_str = JSON.stringify(json.morpheme_type);
                        const total_memory_str = JSON.stringify(json.total_memory);
                        const user_name_str = JSON.stringify(json.user_name);
                        const total_time_str = JSON.stringify(json.total_time);

                        $("#result_info").html('<p><strong>' + morpheme_type_str + ' 분석결과 : '+total_memory_str+'MB사용 / '+total_time_str+'(초) by '+user_name_str+'</strong></p>');
                        for (var i = 0; i < json.result_sentence.length; i++) {
                            var result_list = json.result_sentence[i];
                            var keyword = result_list[0];
                            var tag_info = result_list[1];

                            $("#result_info").append('<p>[' + i + ']번째 분석 결과 : ' + keyword + ', ' + tag_info + '</p>');
                        }
                    }, error: function (xhr, errmsg, err) {
                        console.log(xhr.status + ": " + xhr.responseText);
                    }, complete: function () {
                        $('.load_spinner_class').css('width', '100%').css('height', '100%').css('background-color', '').css('opacity', '1').css('z-index', '0');
                        $('.load_spinner_class *').prop('disabled', false);
                    }
                });
            } else {
                return false;
            }
        }
        */
    </script>

{% endblock %}