core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('product/', include('product.urls')),
    path('support/', include('support.urls')),
    path('photo/', include('photo.urls')),
    path('morpheme/', include('morpheme.urls')),
    path('ml/', include('ml.urls')),
    path('rtc/', include('rtc.urls')),

    path('accounts/register/add/', UserCreateDoneTV.as_view(), name='register_add')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ml/urls.py
from django.urls import path

from ml import views
from ml.views import MLIndexLV, textrank

app_name = 'ml'
urlpatterns = [
    path('', MLIndexLV.as_view(), name='index'),
    path('textrank/', views.textrank, name='textrank'),
]

product/urls.py
from django.urls import path

from .views import *



app_name = 'product'
urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),

    # Example: /add/
    path('add/',
         ProductCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         ProductChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         ProductUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         ProductDeleteView.as_view(), name="delete",
    ),
]

product/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.title

product/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView

from core.views import OwnerRequiredMixin
from .models import Product


class ProductLV(ListView):
    model = Product


class ProductDV(DetailView):
    model = Product


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['title', 'url']
    success_url = reverse_lazy('product:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(ProductCreateView, self).form_valid(form)


class ProductChangeLV(LoginRequiredMixin, ListView):
    template_name = 'product/product_change_list.html'

    def get_queryset(self):
        return Product.objects.filter(owner=self.request.user)


class ProductUpdateView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = Product
    fields = ['title', 'url']
    success_url = reverse_lazy('product:index')


class ProductDeleteView(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('product:index')

product/templates/product/product_change_list.html
{% extends "base.html" %}

{% block title %}product_change_list.html{% endblock %}

{% block content %}

    <h1>Product Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="info">
            <th>Title</th>
            <th>Url</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'product:update' item.id %}">Update</a></td>
            <td><a href="{% url 'product:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

product/templates/product/product_confirm_delete.html
{% extends "base.html" %}

{% block title %}product_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Product Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

{% endblock %}

product/templates/product/product_detail.html
{% extends "base.html" %}

{% block title %}Django Product Detail{% endblock %}

{% block content %}

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>

{% endblock %}

product/templates/product/product_form.html
{% extends "base.html" %}
{% load staticfiles widget_tweaks %}

{% block title %}Product_form.html{% endblock %}

{% block content %}

    <h1>Product Create/Update - {{user}}</h1>
    <p class="text-muted">This is a creation or update form for your product.</p>

    <form class="form-horizontal" action="." method="post">{% csrf_token %}

        <fieldset style="border:1px solid #ccc; padding:20px 0 0 0;">

            <div class="form-group">
                <label for="id_title" class="col-sm-2 control-label">{{ form.title.label}}</label>
                <div class="col-sm-5">
                    {{ form.title|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group">
                <label for="id_url" class="col-sm-2 control-label">{{ form.url.label }}</label>
                <div class="col-sm-5">
                    {{ form.url|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info"/>
                </div>
            </div>

        </fieldset>

    </form>

    <script type="text/javascript">document.getElementById('id_title').focus();</script>

{% endblock %}

product/templates/product/product_list.html
{% extends "base.html" %}

{% block title %}Django Product List{% endblock %}

{% block content %}

    <h1>Product List</h1>

    <ul>
        {% for product in object_list %}
            <li><a href="{% url 'product:detail' product.id %}">{{ product }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}