core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('product/', include('product.urls')),
    path('support/', include('support.urls')),
    path('photo/', include('photo.urls')),
    path('morpheme/', include('morpheme.urls')),
    path('ml/', include('ml.urls')),
    path('rtc/', include('rtc.urls')),

    path('accounts/register/add/', UserCreateDoneTV.as_view(), name='register_add')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ml/urls.py
from django.urls import path

from ml import views
from ml.views import MLIndexLV, textrank

app_name = 'ml'
urlpatterns = [
    path('', MLIndexLV.as_view(), name='index'),
    path('textrank/', views.textrank, name='textrank'),
]

photo/urls.py
from django.urls import path

from .views import *


app_name = 'photo'

urlpatterns = [

    # Example: /
    path('', PhotoLV.as_view(), name='index'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),


    # Example: /photo/add/
    path('photo/add/',
         PhotoCreateView.as_view(), name="photo_add",
    ),

    # Example: /photo/change/
    path('photo/change/',
         PhotoChangeLV.as_view(), name="photo_change",
         ),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/',
         PhotoUpdateView.as_view(), name="photo_update",
    ),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/',
         PhotoDeleteView.as_view(), name="photo_delete",
    ),
]

product/urls.py
from django.urls import path

from .views import *



app_name = 'product'
urlpatterns = [
    path('', ProductLV.as_view(), name='index'),
    path('<int:pk>/', ProductDV.as_view(), name='detail'),

    # Example: /add/
    path('add/',
         ProductCreateView.as_view(), name="add",
    ),

    # Example: /change/
    path('change/',
         ProductChangeLV.as_view(), name="change",
    ),

    # Example: /99/update/
    path('<int:pk>/update/',
         ProductUpdateView.as_view(), name="update",
    ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         ProductDeleteView.as_view(), name="delete",
    ),
]

rtc/urls.py
from django.urls import path

from rtc.views import rtcIndex

app_name = 'rtc'
urlpatterns = [
    path('', rtcIndex.as_view(), name='index'),
    # path('textrank/', views.textrank, name='textrank'),
]

support/urls.py
from django.urls import path

from .views import *

app_name = 'support'
urlpatterns = [

    # Example: /
    path('', SupportLV.as_view(), name='index'),

    # Example: /support/viewer/1
    path('support/pdf_viewer/<int:pk>', SupportPV.as_view(), name='support_pdf_viewer'),

    # Example: /support/ (same as /)
    path('support/', SupportLV.as_view(), name='support_list'),

    # Example: /support/django-example/
    path('support/<slug>/', SupportDV.as_view(), name='support_detail'),

    # Example: /tag/
    path('tag/', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    path('tag/<str:tag>/', SupportTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    path('search/', SearchFormView.as_view(), name='search'),

    # Example: /bssearch/ (Bootstrap Search)
    path('bssearch/', BstrapSearchLV.as_view(), name='bssearch'),

    # Example: /add/
    path('add/',
         SupportCreateView.as_view(), name="add",
         ),

    # Example: /change/
    path('change/',
         SupportChangeLV.as_view(), name="change",
         ),

    # Example: /99/update/
    path('<int:pk>/update/',
         SupportUpdateView.as_view(), name="update",
         ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         SupportDeleteView.as_view(), name="delete",
         ),
]

core/views.py
from .form import UserRegisterForm
from django.urls import reverse_lazy
from django.views.defaults import permission_denied
from django.views.generic import CreateView
from django.views.generic import TemplateView


class PasswordContextMixin:
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            # 'title': self.title,
            **(self.extra_context or {})
        })
        return context

# --- TemplateView
class HomeView(TemplateView):
    template_name = 'home.html'


# --- User Creation
class UserCreateView(PasswordContextMixin, CreateView):
    template_name = 'registration/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('register_done')

    def form_valid(self, form):
        return super(UserCreateView, self).form_valid(form)


class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'


# prevent from other's update/delete
class OwnerRequiredMixin(object):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.owner:
            return permission_denied(self.request,
                                     exception="Only creator of this object can update/delete the object.")
        return self.render_to_response(self.get_context_data())

core/templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% load staticfiles %}

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">

    <!--[if lt IE 9]-->
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <!-- vuejs -->
    <script type="text/javascript" src="https://unpkg.com/vue@2.6.8/dist/vue.js"></script>
    <!-- axios -->
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>


    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% block extra-script %}{% endblock %}

    <!-- Diquest Custom Resources -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">


    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<!-- first line MENU -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">

        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'product:index' %}">Product</a></li>
            <li><a href="{% url 'support:index' %}">Support</a></li>
            <li><a href="{% url 'photo:index' %}">Photo</a></li>
            <li><a href="{% url 'morpheme:morpheme_index' %}">Morpheme</a></li>
            <li><a href="{% url 'ml:index' %}">ML</a></li>
            <li><a href="{% url 'rtc:index' %}">RTC</a></li>

            <li class="menu-item dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">Add<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'product:add' %}">Product</a></li>
                    <li><a href="{% url 'support:add' %}">Support</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'photo:photo_add' %}">Photo</a></li>
                </ul>
            </li>

            <li class="menu-item dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">Change<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'product:change' %}">Product</a></li>
                    <li><a href="{% url 'support:change' %}">Support</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'photo:photo_change' %}">Photo</a></li>
                </ul>
            </li>

            <li class="menu-item dropdown">
                <a class="dropdown-toggle" href="#" data-toggle="dropdown">Util<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'support:search' %}">Search</a></li>
                    <li><a href="{% url 'admin:index' %}">Admin</a></li>
                </ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
                {% if user.is_active %}
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i>
                        {% firstof user.get_short_name user.get_username %}
                        <i class="caret"></i></a>

                    <ul class="dropdown-menu">
                        <li><a href="{% url 'password_change' %}">Change Password</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    </ul>

                {% else %}
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="glyphicon glyphicon-user"></i> Anonymous<i class="caret"></i></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'register' %}">Register</a></li>
                    </ul>
                {% endif %}
            </li>
        </ul>

        <form class="navbar-form navbar-right" action="{% url 'support:bssearch' %}">
            <div class="form-group" style="display:inline;">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" placeholder="검색어를 입력하세요.">
                    <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                </div>
            </div>
        </form>

    </div><!--/.container -->
</nav><!--/.navbar -->

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}


</body>
</html>

core/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}home.html{% endblock %}

{% block extra-style %}

<style type="text/css">

.homewindow {
    background-image: url("{% static 'img/logo.png' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    color: yellow;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}

footer.footer-wrapper {
    background: #456;
    color: #eee;
    line-height: 50px;
}
.footer-wrapper a {
    color: #ff9;    /* footer-right text */
}
.footer-wrapper a:hover {
    color: #0ff;
}

</style>
{% endblock extra-style %}

{% block content %}

    <div class="homewindow">
        <h2 class="title">Django - Diquest Demo Project</h2>
        <h4 class="powered"><i class="glyphicon glyphicon-cog"></i> powered by diquest.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-md-4">
            <h3>Product</h3>
            <p>You can store your own products by Product application. It's also possible to update or delete your products.</p>
        </div>
        <div class="col-md-4">
            <h3>Support</h3>
            <p>This application makes it possible to log daily events or write your own interests such as hobbies, techniques, etc.</p>
        </div>
        <div class="col-md-4">
            <h3>Photo</h3>
            <p>You can upload your own photos through this application. If you delete an photo, all photos within it will be deleted.</p>
        </div>
        <div class="col-md-4">
            <h3>Morpheme</h3>
            <p>You can upload your own photos through this application. If you delete an photo, all photos within it will be deleted.</p>
        </div>
         <div class="col-md-4">
            <h3>ML</h3>
            <p>Machine Learning</p>
        </div>
    </div>

{% endblock content %}

{% block footer %}
<footer class="navbar-fixed-bottom footer-wrapper">

    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <p>
                    Copyright &copy; 2019 Diquest by ekkim
                </p>
            </div>
            <nav class="col-md-7">
                <ul class="list-inline pull-right">
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">link1</a>
                    </li>
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">link2</a>
                    </li>
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">link3</a>
                    </li>
                    <li>
                        <a href="#" rel="tooltip" data-placement="top" data-original-title="준비중입니다">link4</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

</footer>
{% endblock footer %}

{% block extra-script %}
<script>
$(function () {
    $('[rel=tooltip]').tooltip({
        delay: {show:10, hide:100}
    });
});
</script>
{% endblock extra-script %}