core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import HomeView, UserCreateView, UserCreateDoneTV



urlpatterns = [
    path('admin/', admin.site.urls),

    # shkim
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('', HomeView.as_view(), name='home'),
    path('product/', include('product.urls')),
    path('support/', include('support.urls')),
    path('photo/', include('photo.urls')),
    path('morpheme/', include('morpheme.urls')),
    path('ml/', include('ml.urls')),
    path('rtc/', include('rtc.urls')),

    path('accounts/register/add/', UserCreateDoneTV.as_view(), name='register_add')

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ml/urls.py
from django.urls import path

from ml import views
from ml.views import MLIndexLV, textrank

app_name = 'ml'
urlpatterns = [
    path('', MLIndexLV.as_view(), name='index'),
    path('textrank/', views.textrank, name='textrank'),
]

support/urls.py
from django.urls import path

from .views import *

app_name = 'support'
urlpatterns = [

    # Example: /
    path('', SupportLV.as_view(), name='index'),

    # Example: /support/viewer/1
    path('support/pdf_viewer/<int:pk>', SupportPV.as_view(), name='support_pdf_viewer'),

    # Example: /support/ (same as /)
    path('support/', SupportLV.as_view(), name='support_list'),

    # Example: /support/django-example/
    path('support/<slug>/', SupportDV.as_view(), name='support_detail'),

    # Example: /tag/
    path('tag/', TagTV.as_view(), name='tag_cloud'),

    # Example: /tag/tagname/
    path('tag/<str:tag>/', SupportTOL.as_view(), name='tagged_object_list'),

    # Example: /search/
    path('search/', SearchFormView.as_view(), name='search'),

    # Example: /bssearch/ (Bootstrap Search)
    path('bssearch/', BstrapSearchLV.as_view(), name='bssearch'),

    # Example: /add/
    path('add/',
         SupportCreateView.as_view(), name="add",
         ),

    # Example: /change/
    path('change/',
         SupportChangeLV.as_view(), name="change",
         ),

    # Example: /99/update/
    path('<int:pk>/update/',
         SupportUpdateView.as_view(), name="update",
         ),

    # Example: /99/delete/
    path('<int:pk>/delete/',
         SupportDeleteView.as_view(), name="delete",
         ),
]

support/models.py
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from tagging.fields import TagField
import os


class Support(models.Model):
    title = models.CharField('TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('DESCRIPTION', max_length=100, blank=True, help_text='simple description text.')
    content = models.TextField('CONTENT')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    tag = TagField()
    attach_file = models.FileField(
        upload_to='files/%Y/%m',
        name='file',
        default=None,
        null=True,
        blank=True,
        validators=[FileExtensionValidator(["pdf", "zip"], message="Zip 또는 PDF 파일만 허용 가능")]
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        verbose_name = 'support'
        verbose_name_plural = 'supports'
        db_table = 'support_details'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('support:support_detail', args=(self.slug,))

    def get_previous_support(self):
        return self.get_previous_by_modify_date()

    def get_next_support(self):
        return self.get_next_by_modify_date()

    def get_file_absolute_url(self):
        return self.file.url

    def get_file_pdf_id_url(self):
        return reverse('support:support_pdf_viewer', args=(self.id,))

    def get_file_extension(self):
        _, extension = os.path.splitext(self.file.name)
        return extension.replace('.', '')

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(Support, self).save(*args, **kwargs)

support/forms.py
from django import forms


class SupportSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

support/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView
from django.views.generic import FormView
from django.views.generic import ListView, DetailView, TemplateView
from tagging.views import TaggedObjectList

from core.views import OwnerRequiredMixin
from .forms import SupportSearchForm
from .models import Support


# --- TemplateView
class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'


# --- ListView
class SupportLV(ListView):
    model = Support
    template_name = 'support/support_all.html'
    context_object_name = 'supports'
    paginate_by = 3


class SupportTOL(TaggedObjectList):
    model = Support
    template_name = 'tagging/tagging_support_list.html'


# --- DetailView
class SupportDV(DetailView):
    model = Support


# --- PDF View
class SupportPV(DetailView):
    model = Support
    template_name = 'support/support_pdf_viewer.html'


# --- FormView
class SearchFormView(FormView):
    form_class = SupportSearchForm
    template_name = 'support/support_search.html'

    def form_valid(self, form):
        schWord = '%s' % self.request.POST['search_word']
        support_list = Support.objects.filter(
            Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = support_list

        return render(self.request, self.template_name, context)


# --- Bootstrap Search Result
class BstrapSearchLV(ListView):
    template_name = 'support/support_bstrap_search.html'

    def get_queryset(self):
        schWord = '%s' % self.request.GET['search']
        support_list = Support.objects.filter(
            Q(title__icontains=schWord) | Q(description__icontains=schWord) | Q(content__icontains=schWord)).distinct()
        self.search_term = schWord
        self.count = support_list.count()
        return support_list

    def get_context_data(self, **kwargs):
        context = super(BstrapSearchLV, self).get_context_data(**kwargs)
        context['search_term'] = self.search_term
        context['search_count'] = self.count
        return context


class SupportCreateView(LoginRequiredMixin, CreateView):
    model = Support
    fields = ['title', 'slug', 'description', 'content', 'tag', 'file']
    initial = {'slug': 'auto-filling-do-not-input'}
    success_url = reverse_lazy('support:index')

    def form_invalid(self, form):
        return super(SupportCreateView, self).form_invalid(form)

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(SupportCreateView, self).form_valid(form)


class SupportChangeLV(LoginRequiredMixin, ListView):
    template_name = 'support/support_change_list.html'

    def get_queryset(self):
        return Support.objects.filter(owner=self.request.user)


class SupportUpdateView(LoginRequiredMixin, OwnerRequiredMixin, UpdateView):
    model = Support
    fields = ['title', 'slug', 'description', 'content', 'tag', 'file']
    success_url = reverse_lazy('support:index')


class SupportDeleteView(LoginRequiredMixin, OwnerRequiredMixin, DeleteView):
    model = Support
    success_url = reverse_lazy('support:index')

support/templates/support/support_all.html
{% extends "base.html" %}

{% block title %}support_all.html{% endblock %}

{% block content %}

<h1>Support List</h1>

    {% for support in supports %}
        <h2><a href='{{ support.get_absolute_url }}'>{{ support.title }}</a></h2>
        {{ support.modify_date|date:"N d, Y" }}
        <p>{{ support.description }}</p>
            {% if support.file %}
                <a href="{{ support.get_file_absolute_url }} {# support.file.url 사용 가능 #}">다운로드</a>
                {% if support.get_file_extension == 'pdf' %}
                    <a href="{{ support.get_file_pdf_id_url }}">PDF Viewer</a>
                {%  endif %}
            {%  endif %}

    {% endfor %}

    <br/>
    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
            {% endif %}

            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
            {% endif %}
        </span>

    </div>

{% endblock %}

support/templates/support/support_bstrap_search.html
{% extends "base.html" %}

{% block title %}support_bstrap_search.html{% endblock %}

{% block content %}

    <h1>Bootstrap Search Result</h1>

    <br/>

    {% if object_list %}
    <b><i>Search Word({{ search_term }}) - {{ search_count }} supports Found !</i></b>

    {% for support in object_list %}
        <h2><a href='{{ support.get_absolute_url }}'>{{ support.title }}</a></h2>
        {{ support.modify_date|date:"N d, Y" }}
        <p>{{ support.description }}</p>
    {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) - Not Found !</i></b>
    {% endif %}

{% endblock %}

support/templates/support/support_change_list.html
{% extends "base.html" %}

{% block title %}support_change_list.html{% endblock %}

{% block content %}

    <h1>Support Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="info">
            <th>Title</th>
            <th>Description</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'support:update' item.id %}">Update</a></td>
            <td><a href="{% url 'support:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

support/templates/support/support_confirm_delete.html
{% extends "base.html" %}

{% block title %}support_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Support Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

{% endblock %}

support/templates/support/support_detail.html
{% extends "base.html" %}

{% block title %}support_detail.html{% endblock %}

{% block content %}

    <h2>{{ object.title }}</h2>

    <p class="other_supports">
        {% if object.get_previous_by_modify_date %}
        <a href="{{ object.get_previous_support.get_absolute_url }}" title="View previous support">&laquo;--{{ object.get_previous_support }}</a>
        {% endif %}

        {% if object.get_next_by_modify_date %}
        | <a href="{{ object.get_next_support.get_absolute_url }}" title="View next support">{{ object.get_next_support }}--&raquo;</a>
        {% endif %}
    </p>

    <p class="date">{{ object.modify_date|date:"j F Y" }}</p>
    <br/>

    <div class="body">
        {{ object.content|linebreaks }}
    </div>

    <div>
        <b>TAGS: </b>
        {% load tagging_tags %}
        {% tags_for_object object as tags %}
        {% for tag in tags %}
        <a href="{% url 'support:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
        <a href="{% url 'support:tag_cloud' %}"><i>[ TagCloud ]</i></a>
    </div>

    <br/>
    <div>
        {% load disqus_tags %}
        {% disqus_show_comments %}
    </div>

{% endblock %}

support/templates/support/support_form.html
{% extends "base.html" %}
{% load staticfiles widget_tweaks %}

{% block title %}support_form.html{% endblock %}

{% block extra-style %}
<style>
    .slug-grey {background-color: #ddd;}
</style>
{% endblock %}

{% block content %}

    <h1>Support Create/Update - {{user}}</h1>
    <p class="text-muted">This is a creation or update form for your support.</p>

    <form class="form-horizontal" action="." enctype="multipart/form-data" method="post">{% csrf_token %}

        <fieldset style="border:1px solid #ccc; padding:20px 0 0 0;">

            {% for field in form %}

            {% if field.name == "slug" %}
            <div class="form-group">
                <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field|add_class:"slug-grey form-control"|attr:"readonly" }}
                </div>
                {% if field.help_text %}
                <small class="text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>

            {% else %}
            <div class="form-group">
                <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-6">
                    {{ field|add_class:"form-control" }}
                </div>
                {% if field.help_text %}
                <small class="text-muted">{{ field.help_text }}</small>
                {% endif %}
            </div>
            {% endif %}

            {% endfor %}

            {% if form.file.errors %}
                {% for msg in form.file.errors %}
                    <div class="alert alert-warning text-center">
                        <strong>{{ msg|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-5">
                    <input type="submit" value="Submit" class="btn btn-info"/>
                </div>
            </div>

        </fieldset>

    </form>

    <script type="text/javascript">document.getElementById('id_title').focus();
    </script>

{% endblock %}

support/templates/support/support_pdf_viewer.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}support_pdf_viewer.html{% endblock %}

{% block content %}

    <h2>{{ object.title }} PDF Viewer</h2>
    <br/>

    <div class="body">
        <object data="{{ object.get_file_absolute_url }}" type="application/pdf" width="100%" height="700">
            <embed src="{{ object.get_file_absolute_url }}" type="application/pdf" />
        </object>
    </div>

{% endblock %}

support/templates/support/support_search.html
{% extends "base.html" %}
{% load staticfiles widget_tweaks %}

{% block title %}support_search.html{% endblock %}

{% block content %}

    <h1>Support Search</h1>

    <form class="form-inline" action="." method="post" style="margin:20px 0 0 50px;">{% csrf_token %}

        <div class="form-group">
            <label class="control-label" for="id_search_word">{{ form.search_word.label_tag }}</label>
            {{ form.search_word|add_class:"form-control" }}
        </div>
        <input type="submit" value="Submit" class="btn btn-info">

    </form>

    <br/><br/>

    {% if object_list %}
        {% for support in object_list %}
            <h2><a href='{{ support.get_absolute_url }}'>{{ support.title }}</a></h2>
            {{ support.modify_date|date:"N d, Y" }}
            <p>{{ support.description }}</p>
        {% endfor %}

    {% elif search_term %}
        <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}